### ISSUE TITLE
train_shadownet.py : InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [512,547] rhs shape= [512,37]

### ISSUE THREAD

**Issue by mmaka4** [MaybeShewill-CV/CRNN_Tensorflow#142] opened 2018-08-31 21:53 UTC
I am trying to train a model with a new data set, but i get this error. I need a help. What do I miss here ?![ train_shadownet.py ]. Here below is a snippet of error. Thanks in advance.
![error2](https://user-images.githubusercontent.com/42118634/44937246-002aee00-ad81-11e8-90be-aa76c0c26085.jpg)

**Comment by mdbenito** [comment] 2018-08-31 22:05
Duplicate of #136. Wasn't that fixed with the recent changes?

**Comment by mmaka4** [comment] 2018-08-31 22:48
Thanks Brother for your hint, but how can I create those files(character sets) from my labels?

**Comment by mdbenito** [comment] 2018-08-31 23:27
Use the same tool that you use to generate the tfrecords. Run `python tools/write_text_features.py -h`

**Comment by mmaka4** [comment] 2018-09-03 13:42
I worked on that (Struggling to create character sets) through **write_text_features.py** but i get this error: 
python tools/write_text_features.py --dataset_dir /root/CRNN_Tensorflow-master/a --save_dir /root/CRNN_Tensorflow-master/a -c /root/CRNN_Tensorflow-master/data/new
Initializing the dataset provider... done.
Writing tf records for train at /root/CRNN_Tensorflow-master/a/train_feature.tfrecords...
Traceback (most recent call last):
  File "tools/write_text_features.py", line 111, in <module>
    write_tfrecords(provider.train, "train", args.save_dir, args.char_maps)
  File "tools/write_text_features.py", line 78, in write_tfrecords
    all_chars = all_chars.union(reduce(lambda a, b: set(a).union(set(b)), labels))
TypeError: reduce() of empty sequence with no initial value

**Comment by mdbenito** [comment] 2018-09-07 10:28
Note that this error means that `labels` is empty, so `reduce` cannot do anything. This might mean that either your dataset is empty or your labels wrong or something like that

**Comment by mdbenito** [comment] 2018-09-07 10:34
I prepared a PR warning about this, but others need merging previously

**Comment by mdbenito** [comment] 2018-09-10 11:26
This issue now actually contains 2 and both should have been addressed. Maybe it should be closed? @MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment] 2018-09-11 02:31
@mdbenito Yeah I will close it now

**Closed by MaybeShewill-CV** 2018-09-11 02:31 UTC

**Comment by mmaka4** [comment] 2018-09-11 08:53
Thanks a lot Brother @mdbenito it works fine now, though restoring pre-trained weights during training rise errors.

**Comment by mdbenito** [comment] 2018-09-18 07:29
@mmaka4 Can you create a new issue with those errors and post details on how to reproduce? Thanks!
